### ISSUE TITLE
Pallet of user schemas

### ISSUE THREAD

**Issue by Miriman20** [tangram-js/json-editor#3]
Hi,

Great work! "Pallet of user schemas" pane does not show. What should be configured or changed to make it work? 

best miri

**Comment by tangram-js** [comment]
I am sorry that "Pallet of user schemas" is not included in the source code of this project, and I should remove this feature from the README.
I remove that from source code because the JSON Editor in the [json-editor.tangramjs.com](https://json-editor.tangramjs.com/) implement the "Pallet of user schemas" with firbase as backend repository, which is not close related with JSON editing.
